### ISSUE TITLE
landing-page: map issues

### ISSUE THREAD

**Issue by vktrrdk** [deNBI/cloud-portal-webapp#563]
The map on the About page of the landing page should be easier to read. Therefore the font size within the labels with the location names should be adjusted. 

In addition, it should be checked whether the location overview displays all graphics correctly, or whether graphics (such as logos of universities, etc.) are not loaded correctly.

**Comment by donneogod** [comment]
- Adjusted font size to 18px.
- Found no bugs in location overview. Tested in Opera, Chrome, Edge and Firefox.
