### ISSUE TITLE
theming

### ISSUE THREAD

**Issue by eKatchko** [deNBI/cloud-portal-webapp#622]
merge + pr

**Comment by vktrrdk** [comment]
Todos (19.08.2019):
- Add tooltips to minimized sidebar
- adjust brand-logo size and app-footer content when sidebar is minimized
- check padding of main body (cutted elements)
- check colors of alerts and buttons (fixed parameters in the custom.css would be the best, e.g de.NBI-light blue for alert-primary etc.)
- check background color
- make future darkmode possible (idea - toggle-button which toggles a css class
- change transitions for smoother look and feel (especially for the headbar)
- make the user name on the UserInfo page displayable in the headbar (currently remains empty)
